### ISSUE TITLE
Instead of macro it can be done via const fn

### ISSUE THREAD

**Issue by DoumanAsh** [QnnOkabayashi/compiled-uuid#1]
JFYI macros are not necessary for this purpose.
String parsing is possible within `const fn` and since panic is stable recently, you can implement error handling via panic rather than relying on slow proc macro

Example of parsing here: https://github.com/DoumanAsh/uuid/blob/master/src/lib.rs#L419

**Comment by QnnOkabayashi** [comment]
Hi @DoumanAsh, I'm aware that const panics have essentially deprecated this crate. The [`uuid` parser](https://github.com/uuid-rs/uuid/blob/main/src/parser.rs) is going to be a const function in the 1.0 release, which I intend to indicate in this repository once it's released.

**Comment by DoumanAsh** [comment]
Ah I see, if that's your plan then sure
